{
    .cl_cnn0_filename  = "./fc_v4h2/rnet/CNN0.bin",
    .cl_dma0_filename  = "./fc_v4h2/rnet/SDMAC0.bin",
    .cl_dma1_filename  = "./fc_v4h2/rnet/SDMAC1.bin",
    .cl_dma2_filename  = "./fc_v4h2/rnet/SDMAC2.bin",
    .cl_dma3_filename  = "./fc_v4h2/rnet/SDMAC3.bin",
    .weight_filename   = "./fc_v4h2/rnet/weight.bin",
    .orig_weight_addr  = 0xc8000000,
    .orig_output_addr  = 0xd8000000,
    .output_size       = 0x00240000,
    .output_num        = 1,
    .qdata_filename    = "",
    .usecore           = IMPFWDEMO_CNN_ONLY,
    .output_fp32       = 0,
    .target_dsp_core   = 0,
    .out_cf =
    {
        {
            .output_name  = "./fc_v4h2/rnet/output_t.bin",
            .offset       = 0x00000000,
            .ch           = 18,
            .ch_stride    = 131072,
            .width        = 512,
            .height       = 256,
            .bytepp       = 1,
            .scale_factor = 1.000000,
            .zero_point   = 0,
        },
    },
},