{
    .cl_cnn0_filename = "./fc_v4h2/semseg/CNN0.bin",
    .cl_dma0_filename = "./fc_v4h2/semseg/SDMAC0.bin",
    .cl_dma1_filename = "./fc_v4h2/semseg/SDMAC1.bin",
    .cl_dma2_filename = "./fc_v4h2/semseg/SDMAC2.bin",
    .cl_dma3_filename = "./fc_v4h2/semseg/SDMAC3.bin",
    .weight_filename  = "./fc_v4h2/semseg/weight.bin",
    .orig_weight_addr = 0xc8000000,
    .orig_output_addr = 0xdc100000,
    .output_size      = 0x00030000,
    .output_num       = 1,
    .qdata_filename   = "./fc_v4h2/semseg/deploy003401901.cdnnQdata",
    .usecore          = IMPFWDEMO_CNN_ONLY,
    .output_fp32      = 0,
    .target_dsp_core  = 0,
    .out_cf =
    {
        {
            .output_name  = "./fc_v4h2/semseg/conv2d_14.bin",
            .offset       = 0x00000000,
            .ch           = 3,
            .ch_stride    = 65536,
            .width        = 256,
            .height       = 256,
            .bytepp       = 1,
            .scale_factor = 1.000000,
            .zero_point   = 0,
        },
    },
},