{
    .cl_cnn0_filename = "./fc_v4h2/objdet/CNN0.bin",
    .cl_dma0_filename = "./fc_v4h2/objdet/SDMAC0.bin",
    .cl_dma1_filename = "./fc_v4h2/objdet/SDMAC1.bin",
    .cl_dma2_filename = "./fc_v4h2/objdet/SDMAC2.bin",
    .cl_dma3_filename = "./fc_v4h2/objdet/SDMAC3.bin",
    .weight_filename  = "./fc_v4h2/objdet/weight.bin",
    .orig_weight_addr = 0xc8000000,
    .orig_output_addr = 0xdc100000,
    .output_size      = 0x00031800,
    .output_num       = 3,
    .qdata_filename   = "",
    .usecore          = IMPFWDEMO_CNN_ONLY,
    .output_fp32      = 0,
    .target_dsp_core  = 0,
    .out_cf =
    {
        {
            .output_name  = "./fc_v4h2/objdet/output1_t.bin",
            .offset       = 0x00000000,
            .ch           = 96,
            .ch_stride    = 100,
            .width        = 10,
            .height       = 10,
            .bytepp       = 1,
            .scale_factor = 1.000000,
            .zero_point   = 0,
        },
        {
            .output_name  = "./fc_v4h2/objdet/output2_t.bin",
            .offset       = 0x00002800,
            .ch           = 96,
            .ch_stride    = 400,
            .width        = 20,
            .height       = 20,
            .bytepp       = 1,
            .scale_factor = 1.000000,
            .zero_point   = 0,
        },
        {
            .output_name  = "./fc_v4h2/objdet/output3_t.bin",
            .offset       = 0x0000c000,
            .ch           = 96,
            .ch_stride    = 1600,
            .width        = 40,
            .height       = 40,
            .bytepp       = 1,
            .scale_factor = 1.000000,
            .zero_point   = 0,
        },
    },
},