{
    .cl_cnn0_filename = "./fc_v4h2/unet/CNN0.bin",
    .cl_dma0_filename = "./fc_v4h2/unet/SDMAC0.bin",
    .cl_dma1_filename = "./fc_v4h2/unet/SDMAC1.bin",
    .cl_dma2_filename = "./fc_v4h2/unet/SDMAC2.bin",
    .cl_dma3_filename = "./fc_v4h2/unet/SDMAC3.bin",
    .weight_filename  = "./fc_v4h2/unet/weight.bin",
    .orig_weight_addr  = 0xc8000000,
    .orig_output_addr  = 0xd8000000,
    .output_size       = 0x00010000,
    .output_num       = 1,
    .qdata_filename   = "./fc_v4h2/unet/unet_v12_smp_inf003401901.cdnnQdata",
    .usecore          = IMPFWDEMO_CNN_ONLY,
    .output_fp32      = 0,
    .target_dsp_core  = 0,
    .out_cf =
    {
        {
            .output_name  = "./fc_v4h2/unet/_conv_Conv_output_0_t.bin",
            .offset       = 0x00000000,
            .ch           = 3,
            .ch_stride    = 65536,
            .width        = 256,
            .height       = 256,
            .bytepp       = 1,
            .scale_factor = 1.000000,
            .zero_point   = 0,
        },
    },
},